### ISSUE TITLE
Price on Google Play Store

### ISSUE THREAD

**Issue by largraf** [poleguy/cherrybud#6]
It costs about 350 dollars on the Swiss google play store. (actually swiss franks (CHF), which is similar to USD)

**Comment by poleguy** [comment]
Sorry, didn't see this right away. 
Yes, that's the correct price: please don't buy it unless you _really_ want to support me, or are very-very rich and lazy... even then: that version is probably stale, so definitely don't buy it expecting to get the latest cherrybud installed.

Please use the free apk link available from the github main page if you'd like to see the current state of this work.
https://github.com/poleguy/cherrybud

Think of it as a place-holder for now until I get my act together and post this on f-droid and google. 

To be honest, I've also just moved to the pinephone, running real linux, which runs cherrytree natively, so I'll probably put my efforts in fixing things there, and may not spend much time on fixing/working on it for android in the near future.

**Comment by largraf** [comment]
Ah, my bad. I had thought it was a mistake. I already installed it with the apk. Thanks for the answer.
